import '@/styles/globals.css'
import type { AppProps } from 'next/app'
import Head from 'next/head';
import { Quicksand } from 'next/font/google';

const quicksand = Quicksand({ subsets: ['latin'] });

export default function App({ Component, pageProps }: AppProps) {
	return (
		<>
			<Head>
				<title>Red Panda</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" type="image/png" href="logo.png"/>
			</Head>
			<main className={quicksand.className}>
				<Component {...pageProps} />
			</main>
		</>
	);

}
